on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *" # Run every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.1"
      - name: Run HN Bot
        env:
          REDDIT_SECRET: ${{ secrets.REDDIT_SECRET }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
        run: go run .
