on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"
jobs:
  workflow-keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1

  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.24.1"
      - env:
          REDDIT_SECRET: ${{ secrets.REDDIT_SECRET }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
        run: go run .
